Aconfig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('create', views.CreateUserView.as_view(), name='create'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout', views.UserLogoutView.as_view(), name='logout'),
    path('address/add/', views.AddressCreateView.as_view(), name='address_add'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('address/delete/<int:address_id>/', views.AddressDeleteView.as_view(), name='address_delete'),
]

home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products', views.ProductListView.as_view(), name='products'),
    path('product/<int:id>/', views.DetailView.as_view(), name='product'),
]

order/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'order'

urlpatterns = [
    path('cart/detail', views.CartView.as_view(), name='cart_detail'),
    path('cart/add/<int:product_id>/', views.AddToCart.as_view(), name='cart_add'),
    path('cart/update/<int:item_id>/' ,views.UpdateCartItemView.as_view(), name='cart_update' ),
    path('cart/remove/<int:item_id>/', views.RemoveCartItemView.as_view(), name='cart_remove'),

    path('', views.OrderListView.as_view(), name='order_lsit'),
    path('<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('create/', views.CreateOrderView.as_view(), name='create_order'),
    path('<int:order_id>/pay/', views.PaymentView.as_view(), name='payment'),
    path('sales-report/', views.SalesReportView.as_view(), name='sales_report'),
]

templates/inc/footer.html
<footer class="footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-section">
                    <h4>طبیعی‌کالا</h4>
                    <p>عرضه‌کننده مستقیم محصولات سالم، ارگانیک و طبیعی از سراسر ایران.</p>
                </div>
                <div class="footer-section">
                    <h4>لینک‌های سریع</h4>
                    <ul>
                        <li><a href="#">قوانین و مقررات</a></li>
                        <li><a href="#">سوالات متداول</a></li>
                        <li><a href="{% url "accounts:profile" %}">پیگیری سفارش</a></li>
                    </ul>
                </div>
                <div class="footer-section">
                    <h4>تماس با ما</h4>
                    <p>ایمیل: support@tabiikala.com</p>
                    <p>تلفن: ۰۲۱-۱۲۳۴۵۶۷۸</p>
                </div>
            </div>
            <div class="footer-bottom">
                <p>تمامی حقوق برای فروشگاه طبیعی‌کالا محفوظ است © ۱۴۰۴</p>
            </div>
        </div>
    </footer>

templates/inc/navbar.html
    <header class="navbar">
        <div class="container navbar-content">
            <a href="{% url 'home:home' %}" class="brand-logo">طبیعی‌کالا</a>
            <nav class="nav-links">
                <ul>
                    <li><a href="{% url 'home:home' %}">خانه</a></li>
                    <li><a href="{% url "home:products" %}">محصولات</a></li>
                    <li><a href="#">درباره ما</a></li>
                    <li><a href="#">تماس با ما</a></li>
                </ul>
            </nav>
            <div class="nav-icons">             
                <a href="#" aria-label="جستجو"><i class="fas fa-search"></i></a>
                <a href="{% url "order:cart_detail" %}" aria-label="سبد خرید"><i class="fas fa-shopping-cart"></i></a>
                {% if request.user.is_authenticated %}
                <a href="{% url "accounts:logout" %}" aria-label="خروج"><i class='fas fa-sign-out-alt' style='color:red'></i></a>
                <a href="{% url "accounts:profile" %}" aria-label="پروفایل"><i class="fa-regular fa-circle-user"></i> </a>
                
                {% else %}
                <a href="{% url "accounts:login" %}" aria-label="ورود"> <i class='fas fa-sign-in-alt'></i></a>
               
                {% endif %}
                {% if request.user.is_staff %}
                <li><a href="{% url 'order:sales_report' %}">گزارش فروش</a></li>
                {% endif %}
            </div>
        </div>
    </header>